### ISSUE TITLE
ブロックテーマ領域で子テーマが必要なのだろうか議論

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#12]
**参照リンク**
https://twitter.com/richard_tabor/status/1630164596135800833

**感想や配信で伝えたいことなど自由にメモしてください**
# 私は、ブロックテーマの領域で、子テーマのパラダイムが必要であることを十分に納得していないのです。あなたはどう思いますか？

## with [Carolina Nymark](https://twitter.com/carolinapoena)
> どのような変更を加えたいかによります。
theme.json の設定には、サイトエディタで元に戻せないものもありますし（ドロップキャップが欲しいとか）、親テーマが更新されたときに直接ファイルの変更が上書きされます。

> > ああ、コントロールのロックや削除のようなものですね。
そうそう、ブロックテーマで直接ファイルを編集する必要はないはずです。

## with [Shusei Toda](https://twitter.com/shuseitoda)
> それよりも、なぜ必要ないと思うのか、何を考えているのかに興味があります。
テーマ.jsonのオーバーライドがあるため、編集時に子テーマの必要性があると思う。

> > テーマ.jsonの値も含め、ブロックテーマのほぼすべての部分をSite Editorでパーソナライズすることができます。

## with [Fränk Klein](https://twitter.com/fklux)
> WordPressは新しい機能を追加し続け、デフォルトでそれらを有効にしています。
唯一の解決策は、親テーマの theme.json とフィルターで機能をオフにすることです。
新しいtheme.jsonのPHPフィルターを使えば、プラグインで対応できるかもしれません。しかし、それはあまり好きではありません、あまりにも不透明です。

> > JSONに抽象化された機能の一部を有効・無効にするためのUIというのも良いですね。

> カスタムサイトを構築する代理店にとって、インターフェイスを用意し、その情報をデータベースに保存することは、解決策にはならないのです。
変更をソース管理し、異なる環境間で展開できるようにする必要があります。
それに関連して、フルサイト編集に取り組めば取り組むほど、既存のパターンがまだ有用であることがわかります。
ただ、新しいツールやワークフローに適応させる必要があるだけです。
FSEによってテーマは時代遅れになる」という考え方があります。それはないでしょう。

## with [Remkus de Vries](https://twitter.com/remkusdevries)
> リポジトリテーマをベースにしたデザイン・テーマの場合、やはり意味がありますね。

>> カスタムCSSやその他のインタラクションを適用していると推測される？またはサイトエディタによるテーマ設定？

> ディスクの余分な余分なもの。オーバーライドはその方がすっきりします。

## with [@courtneyr_dev](https://twitter.com/courtneyr_dev)
> カスタムテーマ.jsonのデータをまだ解決する方法が必要です。私が未だに子テーマを運用している唯一の理由です。

>> 新しいsettings.customの値を入力する方法のことでしょうか？

> 例えば、テーマのカラーパレットを省いて、独自のカラーパレットを追加したい場合などです。 また、GUIでアクセスするよりも、設定したテーマ.jsonファイルを作成したほうが早いです。

## with [Justin Tadlock](https://twitter.com/justintadlock)
> サイト編集は、親のアップグレードの問題をほとんど解決しています。ユーザーはほとんどの変更をインターフェイスから直接行うことができます。theme.jsonにアクセスできないものもありますが、それはたいていより高度なものです（その場合でも子テーマは必要ですが）...。

> サイト編集では、開発者からユーザーへ拡張されたデザインを出荷するという問題は解決されません。例えば、私がカスタマイズしたTwenty Twenty-Threeテーマを一般ユーザーに提供するにはどうしたらいいでしょうか？ここにあるパターンで可能なカスタマイズもありますが、すべてではありません...。

> また、サイト編集の大きな利点として、孫テーマの夢を本質的に実現することが挙げられます。ユーザーのカスタマイズがデータベースに保存されるため、子テーマをアップグレードできるようになります。

**Comment by inc2734** [comment]
これめっちゃ良い話題ですね。個人的には、例えサイトエディターで全て操作できたとしても、Git 管理したい場合は子テーマ（あるいはプラグインからフック）するしか無いので、ワークフローによっては必要なのではないかと思います。

**Comment by Olein-jp** [comment]
WordPress の昔からの認識からしても、なかなか子テーマ機能をなくすということは難しいでしょうね。

そして、これから徐々にブロックテーマを使ったウェブサイト構築のノウハウも蓄積されていくでしょうし、さまざまな活用方法が考えられていくでしょうね。楽しみ！
