### ISSUE TITLE
Creating a custom block that stores post meta

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#19]
**参照リンク**
https://developer.wordpress.org/news/2023/03/creating-a-custom-block-that-stores-post-meta/

**感想や配信で伝えたいことなど自由にメモしてください**
- 訳したいし試してみたい

**Comment by inc2734** [comment]
Snow Monkey Forms はほぼこれと同じやり方でやってます.

**Comment by Olein-jp** [comment]
ちょっとどんな感じのことが出来るのか実際に試してみたいところです！
