### ISSUE TITLE
ブライアン・ガードナーさんの FSE に関するツイート

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#25]
**参照リンク**
https://twitter.com/bgardner/status/1634404751256240130

**感想や配信で伝えたいことなど自由にメモしてください**

**Comment by Olein-jp** [comment]
マットがRTしてて発見したんだけど、後から見たらキタジマさんもRTしててワロタ

**Comment by inc2734** [comment]
w
や、このツイートのやり方 unitone で真似できそうだなーと思ってメモ代わりにリツイートしたんですよね。
