### ISSUE TITLE
WordPressでお金を稼ぐ方法はたくさんありますが、どのように選択しますか?

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#26]
**参照リンク**
https://twitter.com/hellosammunoz/status/1635620727431757824

**感想や配信で伝えたいことなど自由にメモしてください**
海外の人が WordPress でお金を稼ぐためにはどうしたら良いと考えているかが垣間見られて面白い

**Comment by inc2734** [comment]
この人のクラスタによるのかもですが、プラグイン・テーマ販売の人が結構多いですね。

**Comment by Olein-jp** [comment]
海外の声も見れて新鮮でした。でも、やはり仕事で忙しくてフォーカスできないってコメントもありましたねぇ。
