### ISSUE TITLE
WordPress 6.2 アップデートをフューチャーした動画配信

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#29]
## 配信概要
WordPress 6.2 の変更点を画面共有しながら実際の動作などを交えながら動画配信しても面白そう

## 配信日時
2023年4月4日（火）21:30〜 @hook wp_ Youtube チャンネルにて

## `about.php` の概要
- サイトエディターでの体験向上
- ナビゲーションブロックの体験向上
- ブロックインサーターのデザインが更新
- ブロック設定のサイドバーが「設定」と「スタイル」のタブに整理された
- ブロックテーマのヘッダーとフッターを素早く構築（コレクション追加）
- エディターから Openverse のメディアを検索可能に
- 集中執筆モード
- サイトエディターがベータ版終了
- スタイルブック
- スタイルのコピー＆ペースと
- カスタム CSS
- 上部に固定表示（ヘッダーバーなど `fixed` できる）
- クラシックテーマのウィジェットをブロックテーマにインポート
- テーマにフォントをローカル保存

## 参照資料
- https://www.godaddy.com/garage/whats-new-in-wordpress-6-2/
- #24

**Comment by inc2734** [comment]
> 画面共有しながら実際の動作などを交えながら

↑これが良いと思います！

**Comment by Olein-jp** [comment]
実際のサイトエディターやブロックテーマ、ブロックエディターの操作感を実際に見せて伝えたいですよねー

当日は、instaWP で WordPress を立ち上げておいて、そこにお互いに入って画面共有をしていく形にすることで、バトンタッチや「これこうしたらどうなる？」的なのもスムーズに環境移譲できるかなと想像してます。
