### ISSUE TITLE
Phase 3: Collaboration

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#31]
**参照リンク**
https://make.wordpress.org/core/2023/03/24/phase-3-collaboration/

**感想や配信で伝えたいことなど自由にメモしてください**
- リアルタイムのコラボレーション
- 非同期コラボレーション
- パブリッシング・フロー
- リビジョンの投稿インターフェイス
- 管理画面のデザイン
- ライブラリ、ブロックパターン、スタイル、フォントの管理

**Comment by inc2734** [comment]
お、コレボレーション以外のものもかなりすごそう！

**Comment by Olein-jp** [comment]
動き始めたなーって感じですねー
