### ISSUE TITLE
サイトエディターにおける先頭固定表示の設定方法についての議論

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#32]
**参照リンク**
- https://github.com/WordPress/gutenberg/pull/49085
- https://github.com/WordPress/gutenberg/pull/49219

**感想や配信で伝えたいことなど自由にメモしてください**
サイトエディターで先頭固定表示の設定（sticky）をグループブロックでラップしないといけないという問題について議論されていた。

template parts で直接設定できるようにPRが作られていたが、Revertされたみたい。今後に期待。

**Comment by inc2734** [comment]
議論みてるとおもしろいですね。
