### ISSUE TITLE
What’s new for developers? (April 2023)

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#35]
**参照リンク**
https://developer.wordpress.org/news/2023/04/whats-new-for-developers-april-2023/

**感想や配信で伝えたいことなど自由にメモしてください**

**Comment by inc2734** [comment]
この辺インパクトありますね。

- Grid layout type
- Interactivity API proposal
- Text columns typography support

**Comment by Olein-jp** [comment]
> Interactivity API proposal

これちょっと騒がれていましたが、あんまり意味が分かってませんです…教えてください！

**Comment by inc2734** [comment]
僕も流し読みしただけでよくはわかっていないのですが、コード見た感じだと Angular とか Vue みたいに HTML っぽい感じでインタラクションを追加できるものなのかなと思いました。フロントはみんなが自由にバニラで書いてるからフロントも標準化しようぜってことなんですかね。

**Comment by Olein-jp** [comment]
確かにサンプルコードを見ると vue っぽい感じはしますねー。（くらいのコメントしか出てきませんでした
