### ISSUE TITLE
Per-block CSS with theme.json

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#39]
**参照リンク**
https://developer.wordpress.org/news/2023/04/per-block-css-with-theme-json/

**感想や配信で伝えたいことなど自由にメモしてください**
こんなことできるなんて知らなかった（知ってたかもしれないけど記憶に全くない

でも、もう少し普通にCSSが書ける or 別のところに書いて変数で渡す、みたいなことができると、 `theme.json` 自体が煩雑にならなくて良いかなとは思った。

**Comment by inc2734** [comment]
これは知りませんでした！表現の幅は広がるけどこれどうなんでしょうね。せっかく theme.json や block.json で border とか spacing とか color とか少しずつ整理されながら追加されていっているのに、CSS ならなんでもできちゃうからよくわからないまま全部 CSS プロパティにつっこんどけみたいなことが増えないかな…。

**Comment by Olein-jp** [comment]
<a href="https://github.com/Olein-jp/hook-wp/issues/3">リンクのテスト</a>

**Comment by Olein-jp** [comment]
こうなってくるのであれば、どう theme.json と css とで切り分けていくか、見やすい・分かりやすい構造やコードにするかという点で個性が出てきそうですよね。

個人的には、これは CSS で別ファイルに書けばいいのでは…とか思うところもあります。
