### ISSUE TITLE
Matt 氏の発言について

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#43]
**参照リンク**
翻訳コントリビュートなどに取り組まれている 三宅 さんのブログ
https://blog4.mrsfu.org/2023/05/07/1545/

**感想や配信で伝えたいことなど自由にメモしてください**
先日東京にみえていたマット氏の発言をネタに雑談するの面白そう。
個人的に気になった点としては、

- WordPress（オープンソース） と AI について
- 子どもたちへの教育の活動を WordPress（オープンソース） を通して何ができそうか

**Comment by inc2734** [comment]
今でも Wix をライバル視してるんだなというのが気になりましたw

> 子どもたちへの教育の活動を WordPress（オープンソース） を通して何ができそうか

僕はあんまりピンとこないのですが、オレインさんは CoderDojo もやってらっしゃるのでオレインさんがどう思ったのかは聞きたいですねー。

**Comment by Olein-jp** [comment]
> オレインさんは CoderDojo もやってらっしゃるのでオレインさんがどう思ったのかは聞きたいですねー。

僕の中でも、具体的にどういうことが必要なのか、どういうことができるのかというのはないのですが、そういった部分へのアプローチを WordPress ができれば、コミュニティやプロダクトの持続性や世代交代、はたまたオープンソースへの理解などを底上げできるのかなーという気がしました（気がしただけ
