### ISSUE TITLE
ブロックテーマにおける子テーマについて

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#5]
**参照リンク**
https://fullsiteediting.com/lessons/child-themes/

## 意訳
https://github.com/Olein-jp/hook-wp/wiki/%EF%BC%88%E6%84%8F%E8%A8%B3%EF%BC%89%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%83%86%E3%83%BC%E3%83%9E%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E5%AD%90%E3%83%86%E3%83%BC%E3%83%9E%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by inc2734** [comment]
おぉ、翻訳される、すごい！
これ最近の記事のようですが、6.1 だと未対応な部分があったりしたんですかね（ブロックテーマの子テーマ全くやったことない…）

**Comment by Olein-jp** [comment]
多分動作としては6.1でも同様の動きをすると思いますよー。ただ、この [Full Site Editing](https://fullsiteediting.com/) サイトに子テーマのことをちゃんと書いたリファレンスがなかったので用意されたんだと思ってますー（内容的にバージョンに関して言及しているところもなかったのでー

**Comment by inc2734** [comment]
なるほど！
