### ISSUE TITLE
テンプレート・パーツが「パターン」という名称に変わり、管理できる場所が分かりにくくなったことに関する言及

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#72]
**参照リンク**
- https://twitter.com/carolinapoena/status/1676054415818608640

**感想や配信で伝えたいことなど自由にメモしてください**

**Comment by inc2734** [comment]
あーたしかに。これなんでベータ3で変わったんだろうと思ってました。

**Comment by Olein-jp** [comment]
提案としてはかなーり前からあったみたいですね。全て読めてませんが…

`https://github.com/WordPress/gutenberg/issues/34352`
