### ISSUE TITLE
Twitter アカウントの運用方法の相談

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#87]
hook wp_ Twitter アカウントを作成しました。

https://twitter.com/hookwp_

こちらの運用方法をざっくり決めておいた方が良いかな、と思いましてのご相談です。

## Twitter アカウントについて
アカウント情報は共有している Notion 内にノートを別途用意して共有（ID & PW）しています。

## ツイートの方法
- 上記の情報で各自の端末からもアクセスできるようにしておく
- Tweetdeck（いつ使えなくなるかわかんないけど）でTeam Manage にて共有

## ツイート内容
基本的には以下のような感じで良いのかな？

- hook wp_ からのお知らせ（イベント開催・ポッドキャストや Youtube 動画など更新情報など）
- WordPress に関する情報を共有（RTのみにしておく？）（Resource リストを活用）

**Comment by Olein-jp** [comment]
試しにツイートの最後に僕なら久野の `（く）` と書くようにしてみました。北島さんなら `（き）` みたいな感じ。

**Comment by inc2734** [comment]
こういう系のアカウントと個人アカウント、僕は使い分けで迷っちゃうので Snow Monkey とか unitone のアカウントも作っていないのですが、お知らせ系とかはこういう系のアカウントあるとリツイートもしやすいし便利ですね。ポッドキャストのネタにできそうなのがあったらツイートや RT しておくと良さそうですかね？

> 試しにツイートの最後に僕なら久野の （く） と書くようにしてみました。北島さんなら （き） みたいな感じ。

個人が特定できるなら個人アカウントでやったほうが良いと思うので、これはなくても良くないですかね？

**Comment by Olein-jp** [comment]
> ポッドキャストのネタにできそうなのがあったらツイートや RT しておくと良さそうですかね？

ですねー。これまでのようにイシューは立てると思うので、そのついでにツイートするって流れでいいのかなーと思って、今日ちょっと試してみました。

ただの RT でも良いとは思うのですが、一言二言翻訳して概要を示した上で引用RTもしくは URL 添付ツイートの方が、みている人には優しいのかなぁ…と思って、ちょっと ACF の件を流してみたりしました。

> 個人が特定できるなら個人アカウントでやったほうが良いと思うので、これはなくても良くないですかね？

では、これはなしで。僕は自爆ツイしないように気をつけますw
