### ISSUE TITLE
Intrinsic design, theming, and rethinking how to design with WordPress

### ISSUE THREAD

**Issue by inc2734** [Olein-jp/hook-wp#9]
本質的 web デザインについて。WordPress でデザインすることについて。

**参照リンク**
https://developer.wordpress.org/news/2023/02/intrinsic-design-theming-and-rethinking-how-to-design-with-wordpress/

**感想や配信で伝えたいことなど自由にメモしてください**

**Comment by Olein-jp** [comment]
これからテーマを作る（theme.json 利用なのでクラシックテーマは除外かもだけど）全ての人に読んでもらいたいですよね。

そもそも、Web というものは何か。紙媒体との違いは何か。
そういうところから考えていくと、普段 Web に求めている点でおかしなところがわかったりしますよね。

確かにクライアントワークなどでは、クライアントの理解も必要になってくるのでアレなところはあるかもしれませんが、この考え方を推し進めていくべきだとは個人的には思いますねぇ。

ということで、意訳を Wiki に追加しました！

https://github.com/Olein-jp/hook-wp/wiki/%EF%BC%88%E6%84%8F%E8%A8%B3%EF%BC%89Intrinsic-design-theming-and-rethinking-how-to-design-with-WordPress
