### ISSUE TITLE
What’s new in Gutenberg 16.4? (9 August)

### ISSUE THREAD

**Issue by Olein-jp** [Olein-jp/hook-wp#95]
**参照リンク**
https://make.wordpress.org/core/2023/08/10/whats-new-in-gutenberg-16-4-9-august/

**感想や配信で伝えたいことなど自由にメモしてください**

**Comment by inc2734** [comment]
Auto-Inserting Blocks は気になるし、特に「Allow inserting of unsynced patterns from quick inserter.」は待望の！！

**Comment by Olein-jp** [comment]
> 特に「Allow inserting of unsynced patterns from quick inserter.」は待望の！！

これどんな機能でしたっけ…

**Comment by inc2734** [comment]
クイックインサーター（`/` で表示されるインサーター）にパターンも表示されるようになるみたいです。

**Comment by Olein-jp** [comment]
あー！あれですか！それは正座待機！！！
